// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgtgeftxtodghezcmupk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndGdlZnR4dG9kZ2hlemNtdXBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3MjIwMjAsImV4cCI6MjA0OTI5ODAyMH0.tI4EA55CD9odgp_5SkS3A85xQ1mcYbntY71GufYQkQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);